FROM python:3.11.8-slim-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common \
    libsm6 libxext6 ffmpeg libfontconfig1 libxrender1 libgl1-mesa-glx \
    curl gcc build-essential git

RUN pip install --upgrade pip

RUN pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cpu
RUN pip install accelerate==0.28.0 controlnet-aux==0.0.3 diffusers==0.26.3 gradio==4.21.0 gradio_client==0.12.0  huggingface-hub==0.21.4 numpy==1.26.3 peft==0.7.1 safetensors==0.4.2 tokenizers==0.15.2 transformers==4.38.2 rembg==2.0.56
RUN pip install git+https://github.com/itsdapolice/iopaint


EXPOSE 8080

ENTRYPOINT ["iopaint","start","--model=lama_manga","--device=cpu","--port=8080","--host=0.0.0.0","--enable-interactive-seg","--interactive-seg-device","cpu","--quality=100","--enable-remove-bg","--enable-anime-seg","--enable-mangatextmask"]
